1. Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [17]:
import numpy as np
m = np.array([range(1, 8), range(11, 18), range(21, 28), range(21, 28), range(21, 28), range(31, 38), range(41, 48), range(51, 58), range(61, 68),  range(71, 78),  range(81, 88),  range(91, 98),  range(101, 108)])
m

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

2. Средствами numpy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [13]:
m1 = np.arange(2, 20, 2)
print('m1 - ', m1)
m2 = np.arange(3, 21, 2)
print('m1 - ', m2)
m1*m2

m1 -  [ 2  4  6  8 10 12 14 16 18]
m1 -  [ 3  5  7  9 11 13 15 17 19]


array([  6,  20,  42,  72, 110, 156, 210, 272, 342])

3. Создать две матрицы 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первой матрицы, которые больше соответсвующих (по расположению) значений второй матрицы. Подсчитать сумму этих значений.

In [21]:
import random
m1 = np.random.randint(0, 10, (30,3))
print('m1 - ', m1)
m2 = np.random.randint(0, 10, (30,3))
print('m2 - ', m2)

m1 -  [[4 8 7]
 [6 0 1]
 [3 8 8]
 [4 1 1]
 [9 1 7]
 [6 5 6]
 [0 5 6]
 [7 0 3]
 [9 0 1]
 [3 5 8]
 [1 4 9]
 [9 9 9]
 [9 0 0]
 [8 9 3]
 [7 8 0]
 [3 9 6]
 [8 5 9]
 [8 1 1]
 [4 2 1]
 [2 5 6]
 [0 4 4]
 [3 4 3]
 [1 0 6]
 [3 9 5]
 [8 4 9]
 [5 3 8]
 [8 3 5]
 [6 8 3]
 [3 4 3]
 [1 1 8]]
m2 -  [[0 7 1]
 [5 8 5]
 [3 7 4]
 [3 8 5]
 [9 7 1]
 [6 4 2]
 [9 9 3]
 [6 8 3]
 [2 7 0]
 [7 6 7]
 [3 8 8]
 [4 6 2]
 [3 9 4]
 [3 8 5]
 [2 1 8]
 [2 8 4]
 [1 8 0]
 [0 3 5]
 [8 2 5]
 [1 0 5]
 [2 2 4]
 [8 0 5]
 [2 1 5]
 [8 9 2]
 [1 3 7]
 [0 4 2]
 [9 4 3]
 [1 3 7]
 [2 5 6]
 [5 9 5]]


4. Написать фукнцию, которая для целых значений n и m будет возвращать матрицу размера n на m, заполненую текстурой размера 2 на 2 состоящей из следующий значений:

```
0 1

2 3

```

Пример для n=5 и m = 4:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

5. При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

6. Имеется массив из 10 названий городов. При помощи прихотливой индексации сгенерировать последовательность из 100 элементов представляющих случайный выбор из названий городов.

7. Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)) добиться расставки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

8. Создать двухмерный массив 20 на 3, содержащийслучайные целые числа от 0 до 100. Интерпретируя массив как 20 векторов из 3х компонент, отсортировать массив по длине векторов.

9. Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]. При решении задачи применить технику распространения.

10. Создать массив из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в массиве. Опредлить индекс этого значения.

11. Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

12. Задать два двухмерных массива ar1 и ar2 размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максиум из двух значений, находящихся на аналогичной позиции в массивах ar1, ar2.